global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Configurar alertmanager si se desea
          # - alertmanager:9093

rule_files:
  # Archivos de reglas de alerta
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'nestjs-application'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3000']  # Ajustar según configuración de la aplicación

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']

  # Ejemplo de configuración para múltiples instancias
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: 
  #       - 'localhost:9100'
  #       - 'nodeexporter2:9100'
